# Generated by Django 2.1.2 on 2018-10-31 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('web', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('Adoptado', 'Adoptado'), ('Disponible', 'Disponible'), ('Rescatado', 'Rescatado')], max_length=20)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
